update shit
...

 On branch raum
 Changes to be committed:
	new file:   README.md
	new file:   config/bravia.mk
	modified:   config/common.mk
	modified:   config/common_cdma.mk
	modified:   config/common_gsm.mk
	modified:   config/common_phone.mk
	modified:   config/nfc_enhanced.mk
	modified:   config/theme_chooser.mk
	deleted:    devices/AndroidProducts.mk
	deleted:    devices/raumzero_grouper.mk
	deleted:    devices/raumzero_toro.mk
	modified:   overlay/common/frameworks/base/core/res/res/values/config.xml
	modified:   overlay/common/frameworks/base/packages/SettingsProvider/res/values/defaults.xml
	modified:   overlay/common/frameworks/base/packages/SystemUI/res/values/config.xml
	new file:   overlay/sgs/frameworks/base/core/res/res/values/config.xml
	new file:   overlay/sgs/packages/apps/Settings/res/values/bools.xml
	new file:   prebuilt/common/data/ak/backup/hostapd
	new file:   prebuilt/common/data/ak/frandom_test.sh
	new file:   prebuilt/common/data/ak/init.d/98fq_codel
	new file:   prebuilt/common/data/ak/init.d/98frandom
	new file:   prebuilt/common/data/ak/init.d/99zipalign
	new file:   prebuilt/common/data/ak/recovery_wpa_hostapd.sh
	new file:   prebuilt/common/data/ak/sysctl.conf
	new file:   prebuilt/common/etc/be_movie
	new file:   prebuilt/common/etc/be_photo
	modified:   prebuilt/common/etc/init.d/02kernel
	modified:   prebuilt/common/etc/init.d/05fs
	new file:   prebuilt/common/etc/init.d/98fq_codel
	new file:   prebuilt/common/etc/init.d/99zipalign
	modified:   prebuilt/common/etc/init.raumzero.rc
	new file:   prebuilt/common/etc/permissions/com.sonyericsson.android.SwIqiBmp.xml
	deleted:    prebuilt/common/media/bootanimation-xhdpi.zip
	new file:   tools/adblocker
	new file:   tools/colors
	deleted:    tools/functions
	new file:   tools/getdate
	new file:   tools/java/README
	new file:   tools/java/TabsToWhitespace.java
	modified:   tools/opticharger
	modified:   tools/squisher
	modified:   vendorsetup.sh

diff --git a/tools/squisher b/tools/squisher
--- a/tools/squisher
+++ b/tools/squisher
@@ -1,9 +1,11 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Squish a CM otapackage for distribution
-# cyanogen
 #
-. $ANDROID_BUILD_TOP/vendor/raumzero/tools/functions
+# cyanogen
+# AOKP
+
+. $ANDROID_BUILD_TOP/vendor/raumzero/tools/colors
 
 OUT_TARGET_HOST=`uname -a | grep Darwin`
 if [ -z "$OUT_TARGET_HOST" ]
@@ -14,36 +16,84 @@ then
    SED=sed
 else
    OUT_TARGET_HOST=darwin-x86
-   MD5=md5
+   MD5="md5 -r "
    XARGS="xargs -n 1 -P `sysctl hw.ncpu | awk '{print $2}'`"
    SED=gsed
 fi
 
 if [ -z "$OUT" -o ! -d "$OUT" ]; then
-        echo "ERROR: $0 only works with a full build environment. $OUT should exist."
-        exit 1
+    echo -e "ERROR: $0 only works with a full build environment. $OUT should exist."
+    exit 1
+fi
+
+# out/ dir defined elsewhere
+if [ ! -z $OUT_DIR_COMMON_BASE ]; then
+    TREE_NAME=`basename $ANDROID_BUILD_TOP`
+    OUT_DIR=$OUT_DIR_COMMON_BASE/$TREE_NAME
+else
+    OUT_DIR=$ANDROID_BUILD_TOP/out
+fi
+
+if [ "$TARGET_BUILD_TYPE" = "debug" ]; then
+    OTAPACKAGE=$OUT/${TARGET_PRODUCT}_debug-ota-$TARGET_BUILD_VARIANT.$USER.zip
+elif [ "$TARGET_BUILD_VARIANT" = "userdebug" ]; then
+    OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-eng.$USER.zip
+else
+    OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$USER.zip
+fi
+if [ ! -f "$OTAPACKAGE" ]; then
+    echo -e "$OTAPACKAGE doesn't exist!";
+    exit 1
 fi
 
 OPTICHARGER=$ANDROID_BUILD_TOP/vendor/raumzero/tools/opticharger
 QUIET=-q
 DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
-DELETE_LIBS="libc_malloc_debug_leak.so libc_malloc_debug_qemu.so"
-DELETE_FONTS="MTLmr3m.ttf"
-DELETE_MEDIA="*.qmg"
+
+
+# Some products want a squashfs for xbin for space
+case "$TARGET_PRODUCT" in
+    cyanogen_dream_sapphire) WANT_SQUASHFS=1 ;;
+    *) WANT_SQUASHFS=0 ;;
+esac
+
+if [ "$WANT_SQUASHFS" -eq 1 ]; then
+    fatal=0
+    MKSQUASHFS_VER_REQ=4
+    if type mksquashfs >/dev/null 2>&1; then
+        if mksquashfs -version | grep -q "version $MKSQUASHFS_VER_REQ"; then :; else
+            echo -e
+            echo -e $CL_RED"ERROR: mksquashfs must be at least version $MKSQUASHFS_VER_REQ for this build."$CL_RST
+            fatal=1
+        fi
+    else
+        echo -e
+        echo -e $CL_RED"ERROR: $TARGET_PRODUCT requires mksquashfs."$CL_RST
+        fatal=1
+    fi
+
+    if [ "$fatal" -ne 0 ]; then
+        echo -e
+        echo -e $CL_YLW"       Unoptimized package is still available at"
+        echo -e "         $OTAPACKAGE"$CL_RST
+        exit $fatal
+    fi
+fi
 
 REPACK=$OUT/repack.d
-printf "Sanitizing Environment..."
+echo -e $CL_CYN"Sanitizing environment..."$CL_RST
 rm -rf $REPACK
 mkdir -p $REPACK
-echo
+echo -e
+
 
 # Unpack the otapackage and opticharge all apks
 mkdir $REPACK/ota
 (
 cd $REPACK/ota
-printf "Unpacking $OTAPACKAGE..."
+echo -e $CL_CYN"Unpacking $OTAPACKAGE..."$CL_RST
 unzip $QUIET $OTAPACKAGE
-echo
+echo -e
 
 # Move all apks to the same directory so xargs can
 # use also with framework-res.apk. This allow process
@@ -65,77 +115,96 @@ cd $REPACK/ota
 rm -rf $REPACK/parallel
 )
 
-# Fix build.prop
-$SED -i \
-        -e '/ro\.kernel\.android\.checkjni/d' \
-        -e '/ro\.build\.type/s/eng/user/' \
-        $REPACK/ota/system/build.prop
 
-# Determine what to name the new signed package
-MODVERSION=`sed -n -e'/ro\.raumzero\.version/s/^.*=//p' $OUT/system/build.prop`
-TARGET_PRODUCT_FINAL=`echo $TARGET_PRODUCT | cut -d '_' -f2`
-echo "MODVERSION: $MODVERSION"
-OUTFILE=$OUT/$MODVERSION-$TARGET_PRODUCT_FINAL.zip
+if [ "$WANT_SQUASHFS" -eq 1 ]; then
+    squash_opts="-force-uid 1000 -force-gid 1000 -no-progress -noappend -no-exports -no-recovery"
+    updater=$REPACK/ota/META-INF/com/google/android/updater-script
 
-# Delete unnecessary binaries
-( cd $REPACK/ota/system/bin; echo $DELETE_BINS | xargs rm -f; )
+    # Relocate su
+    cp -a $REPACK/ota/system/xbin $REPACK/_xbin/
+    rm -f $REPACK/_xbin/su $REPACK/ota/system/bin/su
+    mv $REPACK/ota/system/xbin/su $REPACK/ota/system/bin/su
+    chmod -R 555 $REPACK/_xbin/*
 
-# Delete unnecessary libraries
-( cd $REPACK/ota/system/lib; echo $DELETE_LIBS | xargs rm -f; )
+    # Create symlinks for su and busybox (since updater-script can't work on the squashfs filesystem).
+    # Forgive me for the regex hell here.
+    ln -s ../bin/su $REPACK/_xbin/su
+    for link in `sed -n -e's/,//g' -e'/symlink(.*busybox/,/xbin.*);/p' $updater | tr '"' '\n' | sed -n -e'\,/system/xbin/,s,/system/xbin/,,p'`
+    do
+        ln -s busybox $REPACK/_xbin/$link
+    done
 
-# Delete Offline charging mode files
-( cd $REPACK/ota/system/media; echo $DELETE_MEDIA | xargs rm -f; )
+    # Create the squashfs with new and improved symlinkage!
+    mksquashfs $REPACK/_xbin/* $REPACK/_xbin.sqf $squash_opts
+    rm -rf $REPACK/ota/system/xbin/*
+    mv $REPACK/_xbin.sqf $REPACK/ota/system/xbin/xbin.sqf
+    chmod 444 $REPACK/ota/system/xbin/xbin.sqf
 
-if [ "$TARGET_PRODUCT_FINAL" != "infuse4g" ]
-then
-# No need for modem.bin
-rm -f $REPACK/ota/modem.bin
+    # Remove xbin stuff and fix up updater-script
+    $SED -i -e's,system/xbin/su,system/bin/su,g' -e'/xbin/d' $updater
 fi
 
-# No need for media/video
-rm -rf $REPACK/ota/system/media/video
 
-# Delete Unnecessary Fonts
-( cd $REPACK/ota/system/fonts; echo $DELETE_FONTS | xargs rm -f; )
+# Fix build.prop
+$SED -i \
+    -e '/ro\.kernel\.android\.checkjni/d' \
+    -e '/ro\.build\.type/s/eng/user/' \
+    $REPACK/ota/system/build.prop
 
-# No need for tts
-rm -rf $REPACK/ota/system/tts
 
-# No need for srec
-rm -rf $REPACK/ota/system/usr/srec
+# Delete unnecessary binaries
+( cd $REPACK/ota/system/bin; echo -e $DELETE_BINS | xargs rm -f; )
+
+# Delete leftover wireless driver
+# rm -rf $REPACK/ota/system/lib/modules/*/kernel/drivers/net
 
 # No need for recovery
 rm -rf $REPACK/ota/recovery
-rm -rf $REPACK/ota/system/etc/recovery-resource.dat
 
 # Strip modules
 [ -d $REPACK/ota/system/lib/modules ] && \
-        find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded
+    find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded
+
+# Determine what to name the new signed package
+
+#MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $REPACK/ota/system/build.prop`
+VERSION=`sed -n -e'/ro.raumzero.version/s/^.*=//p' $REPACK/ota/system/build.prop`
+MODVERSION="$VERSION"
+OUTFILE=$OUT/$MODVERSION.zip
 
 # Pack it up and sign
-printf "Zipping package..."
+echo -e $CL_CYN"Zipping package..."$CL_RST
 ( cd $REPACK/ota; zip $QUIET -r $REPACK/update.zip . )
-echo
-printf "Signing package..."
+echo -e
+echo -e $CL_CYN"Signing package..."$CL_RST
 SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
-java -Xmx2048m \
-        -jar $OUT/../../../host/$OUT_TARGET_HOST/framework/signapk.jar \
-        -w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
-        $REPACK/update.zip $OUTFILE
-echo
-printf "Cleaning up..."
+java -Xmx3072m \
+    -jar $OUT_DIR/host/$OUT_TARGET_HOST/framework/signapk.jar \
+    -w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
+    $REPACK/update.zip $OUTFILE
+echo -e
+echo -e $CL_CYN"Cleaning up..."$CL_RST
 rm -rf $REPACK
-echo
+echo -e
 
 # Create a md5 checksum image of the repacked package
 (
 img=`basename $OUTFILE`
 cd `dirname $OUTFILE`
 $MD5 $img >$img.md5sum
-echo
-echo "Package complete: $OUTFILE"
-echo "md5: $(cat $img.md5sum | awk '{ print $1 }')"
-echo
+ZIPSIZE=`ls -lah $OUTFILE | awk '{ print $5}' `
+echo -e
+echo -e  $CL_RED" ____ ____ _  _ _  _    ___  ____ ____ ____"
+echo -e $CL_CYN" |__/ |__| |  | |\/|      /  |___ |__/ |  |"
+echo -e $CL_RED" |  \ |  | |__| |  |     /__ |___ |  \ |__|"
+echo -e
+echo -e
+echo -e $CL_CYN"===========-Package complete-==========="$CL_RST
+echo -e $CL_CYN"zip:"$CL_MAG" $OUTFILE"$CL_RST
+echo -e $CL_CYN"md5:"$CL_MAG" $(cat $img.md5sum | awk '{ print $1 }')"$CL_RST
+echo -e $CL_CYN"size:"$CL_MAG" $ZIPSIZE"$CL_RST
+echo -e $CL_CYN"========================================"$CL_RST
+echo -e
 )
 
 exit 0
